name: Build and Release

on:
  workflow_dispatch:
  push:
    tags:        
      - 'v*' 

jobs:
  build:
    uses: xoxfaby/actions/.github/workflows/dotnet-publish.yml@main

  release-nuget:
    needs: build
    uses: xoxfaby/actions/.github/workflows/nuget.yml@main
    secrets:
      NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}

  build-thunderstore:
    needs: build
    uses: xoxfaby/actions/.github/workflows/tcli-build.yml@main
    with:
      version: ${{ needs.build.outputs.version }}

  release-github:
    needs: build-thunderstore
    uses: xoxfaby/actions/.github/workflows/release.yml@main